### ISSUE TITLE
Testing the MediaCachePreload

### ISSUE THREAD

**Issue by multimediaSGT** [WowzaMediaSystems/wse-plugin-mediacachepreload#1]
Hi

I have a wowza engine infrastucture with S3 store system, the main idea would be to have in a Video On Demand enviroment, the possibility of maintain the contain of a file (entirely on cache) if a dissruption occurs with the S3 service and the service and play file is not interrumped.

I have test this module, with a entirely cache file (-1 parameter) in the mediacachepreloadtargets.txt, but i don't see the funcionality with the module, I don't have errors or exceptions on java logged on the wowzastreamingengine_error or wowzastreamingengine_access files with this MediaCachePreload module, I have the PreloadDebugLog property on true. There is some messages with "ServerListenerMediaCachePreload.MediaCacheQueueThread. [Last file change: Wed Mar 06 13:48:03 CET 2019 vs. Wed Mar 06 13:48:03 CET 2019..." but there is not appears more info about it.

If I probe to delete a test file on S3 storage (the file that is configured as cacheable on mediacachepreloadtargets.txt), the file is being active because the Wowza cache system itself about 5-7 mins but after this time the file is not avalible, and is not playable. I don't notice anything on the module.H ow could I debug this? Please tell me some tips.

**Comment by rogerlittin** [comment]
Hi, 
The module is not really designed to be used in the way you are trying to use it. It's designed to preload content that will remain in the cache because it is constantly being viewed. If the content expires due to not being viewed, then it will be flushed from the cache, just like any other piece of content.  

From your description, you would be better off using the [MediaCache Local Content](https://github.com/WowzaMediaSystems/wse-plugin-mediacachelocalcontent) module and storing your important content in a local folder. With this module, it will look locally for the content first and if it doesn't exist, then it will retrieve it from MediaCache. The content retrieved from MediaCache will be cached and expired using your MediaCache TTL limits.

Regards,

Roger.
